# Generated by Django 4.1.7 on 2023-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "t_type",
                    models.CharField(
                        choices=[("ST", "Story"), ("BU", "Bug"), ("SP", "Spike")],
                        default="ST",
                        max_length=2,
                    ),
                ),
                (
                    "t_status",
                    models.CharField(
                        choices=[("TD", "Todo"), ("IP", "In Progress"), ("DO", "Done")],
                        default="TD",
                        max_length=2,
                    ),
                ),
                (
                    "asignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignee",
                        to="members.member",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
