# Generated by Django 4.2 on 2023-04-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to='members.member'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to='members.member'),
        ),
    ]
