/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import MdRenderer from '@/components/MdRenderer';
import { PageHeader } from '@/components/PageHeader';
import { getMDBySlug, getMDSlugs } from '@/data-fetching/fetchMDPaths';

import { Params } from 'next/dist/shared/lib/router/utils/route-matcher';

export default function Home({ markdownData }: { markdownData: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&family=Inconsolata:wght@200;300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <PageHeader />
      <main className={styles.main}>
        <MdRenderer fileContents={markdownData} />
      </main>
    </>
  );
}

export async function getStaticProps({ params }: Params) {
  let { slug } = params;

  if (slug[0] === 'home') {
    slug = ['README.md'];
  }

  const markdownData = getMDBySlug(slug.join('/'));

  return {
    props: { markdownData },
  };
}

export async function getStaticPaths() {
  const mdSlugs = getMDSlugs();

  const paths = mdSlugs.map(mdSlug => ({
    params: { slug: mdSlug.split('/') },
  }));

  return {
    paths,
    fallback: false,
  };
}
